version: '3'

services:
  minio:
    container_name: minio
    image: minio/minio
#    ports: ìîæíî ïðîáðîñèòü ïîðòû íàðóæó ñðàçó, áåç nginx
#      - "9000"
#      - "9001"
    volumes:
      - minio_storage:/data 
# /var/lib/docker/volumes/nginxminio_minio_storage/
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data
#healthcheck service in docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


  nginx:
    container_name: nginx-minio
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio
#healthcheck service in docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_storage: {}
