version: '3'

services:
  minio:
    image: minio/minio
#    ports: можно пробросить порты наружу сразу, без nginx
#      - "9000"
#      - "9001"
    volumes:
      - minio_storage:/data 
# /var/lib/docker/volumes/nginxminio_minio_storage/
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio

volumes:
  minio_storage: {}
