stages:
  - module-pipelines
server1:
  stage: module-pipelines
  trigger:
    include:
      - /server1/.gitlab-ci.yml
    strategy: depend
  only:
    changes: #       server1,   ,     
      - server1/*
server2:
  stage: module-pipelines
  trigger:
    include:
      - /server2/.gitlab-ci.yml
    strategy: depend
  only:
    changes: #       server1,   ,     
      - server2/*
  
